name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Build
      run: |
        mkdir releases
        echo 'first' > releases/first.txt
        echo 'second' > releases/second.txt
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        file: releases/*.txt
        file_glob: true
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}